name: Build / Test

on:
  pull_request:
    branches: [ develop ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2

    - uses: actions/setup-java@v1
      with:
        java-version: '11'

    - name: Build & Test
      uses: burrunan/gradle-cache-action@v1
      with:
        job-id: jdk8-build-test
        arguments: build

    - name: Updload Reports
      uses: actions/upload-artifact@v2
      with:
        name: reports
        path: build/reports
